version: "3"

networks:
  app-tier:
    driver: bridge

volumes:
  kafka_data:
    driver: local

services:
  kafka:
    image: bitnami/kafka:3.3.2
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - app-tier
    environment:
      # Any environment variable beginning with KAFKA_CFG_ will be mapped to
      # its corresponding Apache Kafka key.
      # For example, use KAFKA_CFG_BACKGROUND_THREADS in order to set background.threads
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=HH7wWWdsSguDyPj024NmQA
      # In KRaft mode each Kafka server can be configured as a controller, a broker,
      # or both using the process.roles property.
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # The node ID associated with the roles this process is playing when `process.roles` is non-empty.
      # This is required configuration when running in KRaft mode.
      - KAFKA_CFG_NODE_ID=1
      # Listener List - Comma-separated list of URIs we will listen on and the listener names.
      # URI's are like {LISTENER_NAME}://{hostname}:{port}
      # Leave hostname empty to bind to default interface.
      # If the listener name is not a security protocol, listener.security.protocol.map must also be set.
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      # Map of id/endpoint information for the set of voters in a comma-separated list of {id}@{host}:{port} entries.
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:2181
      # A comma-separated list of the names of the listeners used by the controller.
      # This is required if running in KRaft mode.
      # When communicating with the controller quorum,
      # the broker will always use the first listener in this list.
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Map between listener names and security protocols.
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # NOT SURE OF THESE
      #- KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      #- KAFKA_BROKER_ID=1
    volumes:
      # NOTE: As this is a non-root container, the mounted files and directories must
      # have the proper permissions for the UID 1001.
      - kafka_data:/bitnami
