#!/bin/bash

cd backend

# Run yarn format
npm run format

# Run yarn lint
npm run lint

# Get the exit code of the previous commands
exit_code=$?

# Exit with the appropriate exit code
exit $exit_code
